services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: apepi
      POSTGRES_PASSWORD: apepi_dev
      POSTGRES_DB: apepi
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
